### PR TITLE
1.0 pre2 release

### PR DESCRIPTION
**Pull request by o-smirnov**
Quite a few cleanups -- please see companion release on https://github.com/ratt-ru/radiopadre.

### CODE REVIEW

**Comment by o-smirnov** [comment]
Here's a gotcha, btw: github will happily tag a release with the same name as a branch (this happened to ``1.0-pre1``). Checking out then becomes confusing. Suggest naming branches ``bX.Y`` and/or releases ``vX.y``.

**Comment by Athanaseus** [comment]
@o-smirnov since in Py3 the `ConfigParser` has been renamed to `configparser` (for PEP 8 compliance). We will either need the `six` library (thus becoming a requirement) or do a `try-except` the right module:

`from six.moves import configparser`

or
```
try:
    import configparser
except:
    import ConfigParser
```

**Comment by o-smirnov** [comment]
Either is fine by me, what's best practice?

BTW, please don't release yet, I'll have a few more fixes coming through this week.

**Comment by Athanaseus** [comment]
Both are good. I implemented a `try-except` catching an 'ImortError' exception.

PS: @o-smirnov I will hold my horses.

**Pull request closed without merging**
