### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by Athanaseus**

### CODE REVIEW

**Comment by o-smirnov** [comment]
Nah I'm too heavily invested in f-strings to go below 3.6 now. :) Porting to py3 was bad enough.

On the server side this thing *always* runs in a virtual environment (being a custom jupyter kernel), so the issue is moot. The client package is meant to start the front end on your laptop/desktop. Have you still got 16.04 on that? Well the virtualenv version works perfectly fine there too. :)

**Comment by bennahugo** [comment]
I'm referring to the client yes. It is not a virtualenv issue, it is a system python issue. If you are relying on a 3.6 only feature it is a different story. It just means you force 16.04 users to build python from source or add an external ppa.

**Comment by o-smirnov** [comment]
Well Simon's e-mail of today makes me feel a lot better about this. Out with the old, in with the new. 3.6+ it is.

**Comment by o-smirnov** [comment]
Hehe, 30 minutes into my flight to Cape Town, I realized (a) I only need 30 minutes to make the client 2.7 compatible again, (b) there are weird clusters where old snakes still live, (c) even with a container image, one still needs to run a bit of the client script on the server side to bring up the container.

So, in a screeching handbrake U-turn that would put any recent UK government to shame, I'm gonna make rc2 py2-compatible.

**Pull request merged**
