### PR TITLE
B1.0 pre5

### PR DESCRIPTION
**Pull request by o-smirnov**

### CODE REVIEW

**Comment by o-smirnov** [comment]
OK, will wait for radiopadre to get onto PyPI, then test this, then release.

**Comment by o-smirnov** [comment]
Hmmm @Athanaseus I seem to have mis-releaded pre5 -- the tag actually refers to the pre3 merge. However, I can't find the Delete button for the pre5 release, WTF did it go?

**Comment by o-smirnov** [comment]
Nvm, found it...

**Comment by Athanaseus** [comment]
You have to click the link of the release first. After deleting the release click again on the tag (same) and delete again. It will completely vanish. Then you can make a fresh release.

Screenshot from 2020-03-03 20-40-44

Otherwise, I can do it.

**Comment by o-smirnov** [comment]
Yeah I was clicking on "Edit" first and not getting the button and getting progressively more confused...

OK re-tagged and re-released now.

**Comment by o-smirnov** [comment]
I assume it'll make its way to PyPI automatically now?

**Comment by Athanaseus** [comment]
<a href="http://www.sherv.net/">Big Dancing Banana</a>

**Comment by Athanaseus** [comment]
> I assume it'll make its way to PyPI automatically now?

Yep

**Pull request merged**
